# Taken and customised from: https://github.com/daviddarnes/alembic/blob/main/_config.yml

# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Build settings
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation
# 10. Build settings

# 1. Files excluded from Jekyll builds
exclude:
- .jekyll-cache

# 2. Build settings
markdown: kramdown
remote_theme: daviddarnes/alembic@main
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
  - jemoji
  - jekyll-paginate

# 3. Gem settings
paginate: 2
paginate_path: /page:num

# 4. Jekyll settings
sass:
  style: compressed
permalink: pretty
excerpt_separator: <!-- more -->
timezone: Europe/London

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page

# 7. Site settings
encoding: utf-8
lang: en-GB
title: "spence-m" # Site name or title, also used in jekyll-seo-tag
description: "" # Site description and default description, also used in jekyll-seo-tag
url: "https://spence-m.github.io" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/spence-m/spence-m.github.io"
email: ""
google_analytics: 'G-SC8DB1CY6R'
google_analytics_anonymize_ip: 'true'
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: About
  url: /about

navigation_footer:
- title: ""
